{"timestamp":"2025-09-26T15:17:34.089707","level":"warning","event":"Could not import pandas. Holidays will not be considered.","logger":"airflow.example_dags.plugins.workday"}
{"timestamp":"2025-09-26T15:17:34.181899","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-26T15:17:34.183076","level":"info","event":"Filling up the DagBag from dags/update_db.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-26T15:17:39.483958Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-26T15:17:39.484273Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-26T15:17:39.485024Z","level":"info","event":"Current task name:load_core","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-26T15:17:39.485177Z","level":"info","event":"Dag name:update_db","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-26T15:17:39.794109","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"ValueError","exc_value":"set parameter must be a non-empty dictionary or a ColumnCollection such as the `.c.` collection of a Table object","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/Users/meissagningue/Projects/dev_ia/pipeline_etl_youtube/.venv/lib/python3.11/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/Users/meissagningue/Projects/dev_ia/pipeline_etl_youtube/.venv/lib/python3.11/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/Users/meissagningue/Projects/dev_ia/pipeline_etl_youtube/.venv/lib/python3.11/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/Users/meissagningue/Projects/dev_ia/pipeline_etl_youtube/.venv/lib/python3.11/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/Users/meissagningue/Projects/dev_ia/pipeline_etl_youtube/.venv/lib/python3.11/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/Users/meissagningue/Projects/dev_ia/pipeline_etl_youtube/.venv/lib/python3.11/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/Users/meissagningue/Projects/dev_ia/pipeline_etl_youtube/dags/update_db.py","lineno":140,"name":"load_core"},{"filename":"<string>","lineno":2,"name":"on_conflict_do_update"},{"filename":"/Users/meissagningue/Projects/dev_ia/pipeline_etl_youtube/.venv/lib/python3.11/site-packages/sqlalchemy/sql/base.py","lineno":110,"name":"_generative"},{"filename":"<string>","lineno":2,"name":"on_conflict_do_update"},{"filename":"/Users/meissagningue/Projects/dev_ia/pipeline_etl_youtube/.venv/lib/python3.11/site-packages/sqlalchemy/sql/base.py","lineno":143,"name":"check"},{"filename":"/Users/meissagningue/Projects/dev_ia/pipeline_etl_youtube/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/dml.py","lineno":138,"name":"on_conflict_do_update"},{"filename":"/Users/meissagningue/Projects/dev_ia/pipeline_etl_youtube/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/dml.py","lineno":265,"name":"__init__"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-26T15:17:39.839068Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-26T15:17:39.840185Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-26T15:17:39.840494Z","level":"info","event":"Task:<Task(PythonOperator): load_core>","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-26T15:17:39.840702Z","level":"info","event":"Failure caused by set parameter must be a non-empty dictionary or a ColumnCollection such as the `.c.` collection of a Table object","chan":"stdout","logger":"task"}
